# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-02 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='ordering')),
                ('date_add', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date added')),
            ],
            options={
                'verbose_name_plural': 'dashboards',
                'ordering': ('ordering',),
                'verbose_name': 'dashboard',
            },
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_type', models.CharField(max_length=255, verbose_name='type')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('x', models.PositiveSmallIntegerField(verbose_name='x')),
                ('y', models.PositiveSmallIntegerField(verbose_name='y')),
                ('width', models.PositiveSmallIntegerField(default=1, verbose_name='width')),
                ('height', models.PositiveSmallIntegerField(default=1, verbose_name='height')),
                ('params', models.TextField(blank='', default='', verbose_name='params')),
                ('date_add', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date added')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='jetty.Dashboard', verbose_name='dashboard')),
            ],
            options={
                'verbose_name_plural': 'widgets',
                'ordering': ('y', 'x'),
                'verbose_name': 'widget',
            },
        ),
    ]
