# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-22 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jetty', '0002_viewsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.TextField(blank='', default='', verbose_name='items')),
                ('date_add', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date added')),
            ],
            options={
                'verbose_name_plural': 'menu settings',
                'verbose_name': 'menu settings',
            },
        ),
    ]
