# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-31 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jetty', '0003_menusettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewsettings',
            name='layout',
        ),
        migrations.AddField(
            model_name='viewsettings',
            name='params',
            field=models.TextField(blank=True, default='', verbose_name='params'),
        ),
        migrations.AddField(
            model_name='viewsettings',
            name='view',
            field=models.CharField(blank=True, default='change', max_length=255, verbose_name='view'),
        ),
        migrations.AlterField(
            model_name='menusettings',
            name='items',
            field=models.TextField(blank=True, default='', verbose_name='items'),
        ),
        migrations.AlterField(
            model_name='viewsettings',
            name='model',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='model'),
        ),
        migrations.AlterField(
            model_name='widget',
            name='params',
            field=models.TextField(blank=True, default='', verbose_name='params'),
        ),
    ]
