# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-02 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jetty', '0004_auto_20180731_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(blank=True, default='', max_length=30, verbose_name='project')),
                ('token', models.UUIDField(verbose_name='token')),
                ('date_add', models.DateTimeField(verbose_name='date added')),
            ],
            options={
                'verbose_name': 'token',
                'verbose_name_plural': 'tokens',
            },
        ),
    ]
